EESchema Schematic File Version 2
LIBS:4xxx
LIBS:4xxx_IEEE
LIBS:74xGxx
LIBS:74xx
LIBS:74xx_IEEE
LIBS:ac-dc
LIBS:actel
LIBS:adc-dac
LIBS:allegro
LIBS:Altera
LIBS:Amplifier_Audio
LIBS:Amplifier_Buffer
LIBS:Amplifier_Current
LIBS:Amplifier_Difference
LIBS:Amplifier_Instrumentation
LIBS:Amplifier_Operational
LIBS:Amplifier_Video
LIBS:Analog
LIBS:Analog_ADC
LIBS:Analog_DAC
LIBS:analog_devices
LIBS:Analog_Switch
LIBS:analog_switches
LIBS:atmel
LIBS:Audio
LIBS:Battery_Management
LIBS:bbd
LIBS:bosch
LIBS:brooktre
LIBS:cmos_ieee
LIBS:cmos4000
LIBS:Comparator
LIBS:conn
LIBS:Connector
LIBS:Connector_Generic
LIBS:Connector_Generic_MountingPin
LIBS:Connector_Generic_Shielded
LIBS:contrib
LIBS:Converter_ACDC
LIBS:Converter_DCDC
LIBS:CPLD_Altera
LIBS:CPLD_Xilinx
LIBS:CPU
LIBS:CPU_NXP_6800
LIBS:CPU_NXP_68000
LIBS:CPU_PowerPC
LIBS:cypress
LIBS:dc-dc
LIBS:Device
LIBS:digital-audio
LIBS:Diode
LIBS:Diode_Bridge
LIBS:Diode_Laser
LIBS:display
LIBS:Display_Character
LIBS:Display_Graphic
LIBS:dk_Addressable-Specialty
LIBS:dk_Alarms-Buzzers-and-Sirens
LIBS:dk_Automotive-Relays
LIBS:dk_Balun
LIBS:dk_Barrel-Audio-Connectors
LIBS:dk_Battery-Holders-Clips-Contacts
LIBS:dk_Clock-Timing-Clock-Generators-PLLs-Frequency-Synthesizers
LIBS:dk_Clock-Timing-Programmable-Timers-and-Oscillators
LIBS:dk_Clock-Timing-Real-Time-Clocks
LIBS:dk_Coaxial-Connectors-RF
LIBS:dk_Current-Transducers
LIBS:dk_Data-Acquisition-ADCs-DACs-Special-Purpose
LIBS:dk_Data-Acquisition-Analog-to-Digital-Converters-ADC
LIBS:dk_Data-Acquisition-Digital-Potentiometers
LIBS:dk_Data-Acquisition-Digital-to-Analog-Converters-DAC
LIBS:dk_Data-Acquisition-Touch-Screen-Controllers
LIBS:dk_DC-DC-Converters
LIBS:dk_Digital-Isolators
LIBS:dk_Diodes-Bridge-Rectifiers
LIBS:dk_Diodes-Rectifiers-Arrays
LIBS:dk_Diodes-Rectifiers-Single
LIBS:dk_Diodes-Zener-Single
LIBS:dk_Display-Modules-LCD-OLED-Graphic
LIBS:dk_Display-Modules-LED-Character-and-Numeric
LIBS:dk_D-Sub-Connectors
LIBS:dk_Embedded-Microcontrollers
LIBS:dk_Encoders
LIBS:dk_Evaluation-Boards-Sensors
LIBS:dk_Ferrite-Beads-and-Chips
LIBS:dk_Fixed-Inductors
LIBS:dk_Fuses
LIBS:dk_Gas-Sensors
LIBS:dk_Humidity-Moisture-Sensors
LIBS:dk_Image-Sensors-Camera
LIBS:dk_Infrared-UV-Visible-Emitters
LIBS:dk_Inrush-Current-Limiters-ICL
LIBS:dk_Interface-Analog-Switches-Multiplexers-Demultiplexers
LIBS:dk_Interface-Analog-Switches-Special-Purpose
LIBS:dk_Interface-Controllers
LIBS:dk_Interface-Drivers-Receivers-Transceivers
LIBS:dk_Interface-I-O-Expanders
LIBS:dk_Interface-Modules
LIBS:dk_Interface-Sensor-and-Detector-Interfaces
LIBS:dk_Interface-Sensor-Capacitive-Touch
LIBS:dk_Interface-Specialized
LIBS:dk_LED-Indication-Discrete
LIBS:dk_LEDs-Circuit-Board-Indicators-Arrays-Light-Bars-Bar-Graphs
LIBS:dk_Linear-Amplifiers-Audio
LIBS:dk_Linear-Amplifiers-Instrumentation-OP-Amps-Buffer-Amps
LIBS:dk_Linear-Comparators
LIBS:dk_Logic-Buffers-Drivers-Receivers-Transceivers
LIBS:dk_Logic-Flip-Flops
LIBS:dk_Logic-Gates-and-Inverters
LIBS:dk_Logic-Multivibrators
LIBS:dk_Logic-Shift-Registers
LIBS:dk_Logic-Signal-Switches-Multiplexers-Decoders
LIBS:dk_Logic-Translators-Level-Shifters
LIBS:dk_Magnetic-Sensors-Compass-Magnetic-Field-Modules
LIBS:dk_Magnetic-Sensors-Linear-Compass-ICs
LIBS:dk_Magnetic-Sensors-Switches-Solid-State
LIBS:dk_Memory
LIBS:dk_Memory-Connectors-PC-Card-Sockets
LIBS:dk_Microphones
LIBS:dk_Modular-Connectors-Jacks
LIBS:dk_Modular-Connectors-Jacks-With-Magnetics
LIBS:dk_Motion-Sensors-Accelerometers
LIBS:dk_Motion-Sensors-IMUs-Inertial-Measurement-Units
LIBS:dk_Motion-Sensors-Tilt-Switches
LIBS:dk_Navigation-Switches-Joystick
LIBS:dk_Optical-Sensors-Ambient-Light-IR-UV-Sensors
LIBS:dk_Optical-Sensors-Photo-Detectors-Remote-Receiver
LIBS:dk_Optical-Sensors-Photodiodes
LIBS:dk_Optical-Sensors-Phototransistors
LIBS:dk_Optical-Sensors-Reflective-Analog-Output
LIBS:dk_Optoisolators-Logic-Output
LIBS:dk_Optoisolators-Transistor-Photovoltaic-Output
LIBS:dk_Optoisolators-Triac-SCR-Output
LIBS:dk_Oscillators
LIBS:dk_PMIC-AC-DC-Converters-Offline-Switchers
LIBS:dk_PMIC-Battery-Chargers
LIBS:dk_PMIC-Battery-Management
LIBS:dk_PMIC-Current-Regulation-Management
LIBS:dk_PMIC-Full-Half-Bridge-Drivers
LIBS:dk_PMIC-Gate-Drivers
LIBS:dk_PMIC-LED-Drivers
LIBS:dk_PMIC-Motor-Drivers-Controllers
LIBS:dk_PMIC-OR-Controllers-Ideal-Diodes
LIBS:dk_PMIC-Power-Distribution-Switches-Load-Drivers
LIBS:dk_PMIC-Power-Management-Specialized
LIBS:dk_PMIC-RMS-to-DC-Converters
LIBS:dk_PMIC-Supervisors
LIBS:dk_PMIC-Thermal-Management
LIBS:dk_PMIC-V-F-and-F-V-Converters
LIBS:dk_PMIC-Voltage-Reference
LIBS:dk_PMIC-Voltage-Regulators-DC-DC-Switching-Controllers
LIBS:dk_PMIC-Voltage-Regulators-DC-DC-Switching-Regulators
LIBS:dk_PMIC-Voltage-Regulators-Linear
LIBS:dk_PMIC-Voltage-Regulators-Special-Purpose
LIBS:dk_Power-Relays-Over-2-Amps
LIBS:dk_Pressure-Sensors-Transducers
LIBS:dk_Programmable-Oscillators
LIBS:dk_Pushbutton-Switches
LIBS:dk_Rectangular-Connectors-Headers-Male-Pins
LIBS:dk_Reed-Relays
LIBS:dk_Resistor-Networks-Arrays
LIBS:dk_RF-Amplifiers
LIBS:dk_RF-Antennas
LIBS:dk_RF-Demodulators
LIBS:dk_RF-Detectors
LIBS:dk_RF-Evaluation-and-Development-Kits-Boards
LIBS:dk_RFID-RF-Access-Monitoring-ICs
LIBS:dk_RF-Receivers
LIBS:dk_RF-Switches
LIBS:dk_RF-Transceiver-ICs
LIBS:dk_RF-Transceiver-Modules
LIBS:dk_RF-Transmitters
LIBS:dk_Rotary-Potentiometers-Rheostats
LIBS:dk_Sensors-Transducers_Accessories
LIBS:dk_Signal-Relays-Up-to-2-Amps
LIBS:dk_Slide-Switches
LIBS:dk_Solid-State-Relays
LIBS:dk_Specialized-ICs
LIBS:dk_Specialized-Sensors
LIBS:dk_Surge-Suppression-ICs
LIBS:dk_Tactile-Switches
LIBS:dk_Temperature-Sensors-Analog-and-Digital-Output
LIBS:dk_Thermal-Cutoffs-Thermal-Fuses
LIBS:dk_Thyristors-DIACs-SIDACs
LIBS:dk_Thyristors-SCRs
LIBS:dk_Thyristors-TRIACs
LIBS:dk_Toggle-Switches
LIBS:dk_Transistors-Bipolar-BJT-Arrays
LIBS:dk_Transistors-Bipolar-BJT-RF
LIBS:dk_Transistors-Bipolar-BJT-Single
LIBS:dk_Transistors-Bipolar-BJT-Single-Pre-Biased
LIBS:dk_Transistors-FETs-MOSFETs-Arrays
LIBS:dk_Transistors-FETs-MOSFETs-RF
LIBS:dk_Transistors-FETs-MOSFETs-Single
LIBS:dk_Transistors-JFETs
LIBS:dk_Trimmer-Potentiometers
LIBS:dk_TVS-Diodes
LIBS:dk_TVS-Mixed-Technology
LIBS:dk_USB-DVI-HDMI-Connectors
LIBS:Driver_Display
LIBS:Driver_FET
LIBS:Driver_LED
LIBS:Driver_Motor
LIBS:Driver_Relay
LIBS:dsp
LIBS:DSP_Freescale
LIBS:DSP_Microchip_DSPIC33
LIBS:DSP_Motorola
LIBS:DSP_Texas
LIBS:elec-unifil
LIBS:ESD_Protection
LIBS:Filter
LIBS:FPGA_Microsemi
LIBS:FPGA_Xilinx
LIBS:FPGA_Xilinx_Artix7
LIBS:FPGA_Xilinx_Kintex7
LIBS:FPGA_Xilinx_Spartan6
LIBS:FPGA_Xilinx_Virtex5
LIBS:FPGA_Xilinx_Virtex6
LIBS:FPGA_Xilinx_Virtex7
LIBS:ftdi
LIBS:gennum
LIBS:GPU
LIBS:Graphic
LIBS:graphic_symbols
LIBS:hc11
LIBS:infineon
LIBS:intel
LIBS:Interface
LIBS:Interface_CAN_LIN
LIBS:Interface_CurrentLoop
LIBS:Interface_Ethernet
LIBS:Interface_Expansion
LIBS:Interface_HID
LIBS:Interface_LineDriver
LIBS:Interface_Optical
LIBS:Interface_Telecom
LIBS:Interface_UART
LIBS:Interface_USB
LIBS:intersil
LIBS:ir
LIBS:Isolator
LIBS:Isolator_Analog
LIBS:Jumper
LIBS:Lattice
LIBS:LED
LIBS:leds
LIBS:LEM
LIBS:linear
LIBS:Logic_LevelTranslator
LIBS:Logic_Programmable
LIBS:maxim
LIBS:MCU_AnalogDevices
LIBS:MCU_Cypress
LIBS:MCU_Espressif
LIBS:MCU_Intel
LIBS:MCU_Microchip_8051
LIBS:MCU_Microchip_ATmega
LIBS:MCU_Microchip_ATtiny
LIBS:MCU_Microchip_AVR
LIBS:MCU_Microchip_PIC10
LIBS:MCU_Microchip_PIC12
LIBS:MCU_Microchip_PIC16
LIBS:MCU_Microchip_PIC18
LIBS:MCU_Microchip_PIC24
LIBS:MCU_Microchip_PIC32
LIBS:MCU_Microchip_SAME
LIBS:MCU_Microchip_SAML
LIBS:MCU_Module
LIBS:MCU_Nordic
LIBS:MCU_NXP_ColdFire
LIBS:MCU_NXP_HC11
LIBS:MCU_NXP_HC12
LIBS:MCU_NXP_HCS12
LIBS:MCU_NXP_Kinetis
LIBS:MCU_NXP_LPC
LIBS:MCU_NXP_MAC7100
LIBS:MCU_NXP_MCore
LIBS:MCU_NXP_S08
LIBS:MCU_Parallax
LIBS:MCU_SiFive
LIBS:MCU_SiliconLabs
LIBS:MCU_ST_STM8
LIBS:MCU_ST_STM32F0
LIBS:MCU_ST_STM32F1
LIBS:MCU_ST_STM32F2
LIBS:MCU_ST_STM32F3
LIBS:MCU_ST_STM32F4
LIBS:MCU_ST_STM32F7
LIBS:MCU_ST_STM32H7
LIBS:MCU_ST_STM32L0
LIBS:MCU_ST_STM32L1
LIBS:MCU_ST_STM32L4
LIBS:MCU_ST_STM32L4+
LIBS:MCU_Texas
LIBS:MCU_Texas_MSP430
LIBS:Mechanical
LIBS:memory
LIBS:Memory_Controller
LIBS:Memory_EEPROM
LIBS:Memory_EPROM
LIBS:Memory_Flash
LIBS:Memory_NVRAM
LIBS:Memory_RAM
LIBS:Memory_ROM
LIBS:Memory_UniqueID
LIBS:microchip
LIBS:microchip_dspic33dsc
LIBS:microchip_pic10mcu
LIBS:microchip_pic12mcu
LIBS:microchip_pic16mcu
LIBS:microchip_pic18mcu
LIBS:microchip_pic24mcu
LIBS:microchip_pic32mcu
LIBS:microcontrollers
LIBS:modules
LIBS:Motor
LIBS:motor_drivers
LIBS:motorola
LIBS:motors
LIBS:msp430
LIBS:nordicsemi
LIBS:nxp
LIBS:nxp_armmcu
LIBS:onsemi
LIBS:opto
LIBS:Oscillator
LIBS:Oscillators
LIBS:philips
LIBS:Potentiometer_Digital
LIBS:power
LIBS:Power_Management
LIBS:Power_Protection
LIBS:Power_Supervisor
LIBS:powerint
LIBS:pspice
LIBS:Reference_Current
LIBS:Reference_Voltage
LIBS:references
LIBS:regul
LIBS:Regulator_Controller
LIBS:Regulator_Current
LIBS:Regulator_Linear
LIBS:Regulator_SwitchedCapacitor
LIBS:Regulator_Switching
LIBS:Relay
LIBS:Relay_SolidState
LIBS:relays
LIBS:RF
LIBS:RF_AM_FM
LIBS:RF_Amplifier
LIBS:RF_Bluetooth
LIBS:RF_GPS
LIBS:RF_Mixer
LIBS:RF_Module
LIBS:RF_RFID
LIBS:RF_Switch
LIBS:RF_WiFi
LIBS:RF_ZigBee
LIBS:rfcom
LIBS:RFSolutions
LIBS:Sensor
LIBS:Sensor_Audio
LIBS:Sensor_Current
LIBS:Sensor_Gas
LIBS:Sensor_Humidity
LIBS:Sensor_Magnetic
LIBS:Sensor_Motion
LIBS:Sensor_Optical
LIBS:Sensor_Pressure
LIBS:Sensor_Proximity
LIBS:Sensor_Temperature
LIBS:Sensor_Touch
LIBS:Sensor_Voltage
LIBS:sensors
LIBS:silabs
LIBS:siliconi
LIBS:stm8
LIBS:stm32
LIBS:supertex
LIBS:Switch
LIBS:switches
LIBS:texas
LIBS:Timer
LIBS:Timer_PLL
LIBS:Timer_RTC
LIBS:transf
LIBS:Transformer
LIBS:Transistor_Array
LIBS:Transistor_BJT
LIBS:Transistor_FET
LIBS:Transistor_IGBT
LIBS:transistors
LIBS:Triac_Thyristor
LIBS:ttl_ieee
LIBS:Valve
LIBS:valves
LIBS:Video
LIBS:wiznet
LIBS:Worldsemi
LIBS:Xicor
LIBS:xilinx
LIBS:zetex
LIBS:Zilog
LIBS:device
LIBS:audio
LIBS:interface
LIBS:ch340t
LIBS:ld33v
LIBS:LPC1114_LED_Cube-cache
EELAYER 25 0
EELAYER END
$Descr A4 11693 8268
encoding utf-8
Sheet 2 2
Title ""
Date ""
Rev ""
Comp ""
Comment1 ""
Comment2 ""
Comment3 ""
Comment4 ""
$EndDescr
Text HLabel 2950 2800 0    60   Input ~ 0
LAYER_0_ON
Text GLabel 3000 2300 0    60   Input ~ 0
V5
$Comp
L GND #PWR?
U 1 1 5B358FD5
P 3050 3800
F 0 "#PWR?" H 3050 3550 50  0001 C CNN
F 1 "GND" H 3050 3650 50  0000 C CNN
F 2 "" H 3050 3800 50  0001 C CNN
F 3 "" H 3050 3800 50  0001 C CNN
	1    3050 3800
	1    0    0    -1  
$EndComp
Text HLabel 4450 2800 2    60   Output ~ 0
LAYER_0_PWR
$EndSCHEMATC
