update=6/15/2018 9:58:11 PM
version=1
last_client=kicad
[pcbnew]
version=1
LastNetListRead=
UseCmpFile=1
PadDrill=0.600000000000
PadDrillOvalY=0.600000000000
PadSizeH=1.500000000000
PadSizeV=1.500000000000
PcbTextSizeV=1.500000000000
PcbTextSizeH=1.500000000000
PcbTextThickness=0.300000000000
ModuleTextSizeV=1.000000000000
ModuleTextSizeH=1.000000000000
ModuleTextSizeThickness=0.150000000000
SolderMaskClearance=0.000000000000
SolderMaskMinWidth=0.000000000000
DrawSegmentWidth=0.200000000000
BoardOutlineThickness=0.100000000000
ModuleOutlineThickness=0.150000000000
[cvpcb]
version=1
NetIExt=net
[general]
version=1
[eeschema]
version=1
LibDir=
[eeschema/libraries]
LibName1=C:/Program Files/KiCad/share/kicad/library/4xxx
LibName2=C:/Program Files/KiCad/share/kicad/library/4xxx_IEEE
LibName3=C:/Program Files/KiCad/share/kicad/library/74xGxx
LibName4=C:/Program Files/KiCad/share/kicad/library/74xx
LibName5=C:/Program Files/KiCad/share/kicad/library/74xx_IEEE
LibName6=C:/Program Files/KiCad/share/kicad/library/ac-dc
LibName7=C:/Program Files/KiCad/share/kicad/library/actel
LibName8=C:/Program Files/KiCad/share/kicad/library/adc-dac
LibName9=C:/Program Files/KiCad/share/kicad/library/allegro
LibName10=C:/Program Files/KiCad/share/kicad/library/Altera
LibName11=C:/Program Files/KiCad/share/kicad/library/Amplifier_Audio
LibName12=C:/Program Files/KiCad/share/kicad/library/Amplifier_Buffer
LibName13=C:/Program Files/KiCad/share/kicad/library/Amplifier_Current
LibName14=C:/Program Files/KiCad/share/kicad/library/Amplifier_Difference
LibName15=C:/Program Files/KiCad/share/kicad/library/Amplifier_Instrumentation
LibName16=C:/Program Files/KiCad/share/kicad/library/Amplifier_Operational
LibName17=C:/Program Files/KiCad/share/kicad/library/Amplifier_Video
LibName18=C:/Program Files/KiCad/share/kicad/library/Analog
LibName19=C:/Program Files/KiCad/share/kicad/library/Analog_ADC
LibName20=C:/Program Files/KiCad/share/kicad/library/Analog_DAC
LibName21=C:/Program Files/KiCad/share/kicad/library/analog_devices
LibName22=C:/Program Files/KiCad/share/kicad/library/Analog_Switch
LibName23=C:/Program Files/KiCad/share/kicad/library/analog_switches
LibName24=C:/Program Files/KiCad/share/kicad/library/atmel
LibName25=C:/Program Files/KiCad/share/kicad/library/Audio
LibName26=C:/Program Files/KiCad/share/kicad/library/Battery_Management
LibName27=C:/Program Files/KiCad/share/kicad/library/bbd
LibName28=C:/Program Files/KiCad/share/kicad/library/bosch
LibName29=C:/Program Files/KiCad/share/kicad/library/brooktre
LibName30=C:/Program Files/KiCad/share/kicad/library/cmos_ieee
LibName31=C:/Program Files/KiCad/share/kicad/library/cmos4000
LibName32=C:/Program Files/KiCad/share/kicad/library/Comparator
LibName33=C:/Program Files/KiCad/share/kicad/library/conn
LibName34=C:/Program Files/KiCad/share/kicad/library/Connector
LibName35=C:/Program Files/KiCad/share/kicad/library/Connector_Generic
LibName36=C:/Program Files/KiCad/share/kicad/library/Connector_Generic_MountingPin
LibName37=C:/Program Files/KiCad/share/kicad/library/Connector_Generic_Shielded
LibName38=C:/Program Files/KiCad/share/kicad/library/contrib
LibName39=C:/Program Files/KiCad/share/kicad/library/Converter_ACDC
LibName40=C:/Program Files/KiCad/share/kicad/library/Converter_DCDC
LibName41=C:/Program Files/KiCad/share/kicad/library/CPLD_Altera
LibName42=C:/Program Files/KiCad/share/kicad/library/CPLD_Xilinx
LibName43=C:/Program Files/KiCad/share/kicad/library/CPU
LibName44=C:/Program Files/KiCad/share/kicad/library/CPU_NXP_6800
LibName45=C:/Program Files/KiCad/share/kicad/library/CPU_NXP_68000
LibName46=C:/Program Files/KiCad/share/kicad/library/CPU_PowerPC
LibName47=C:/Program Files/KiCad/share/kicad/library/cypress
LibName48=C:/Program Files/KiCad/share/kicad/library/dc-dc
LibName49=C:/Program Files/KiCad/share/kicad/library/Device
LibName50=C:/Program Files/KiCad/share/kicad/library/digital-audio
LibName51=C:/Program Files/KiCad/share/kicad/library/Diode
LibName52=C:/Program Files/KiCad/share/kicad/library/Diode_Bridge
LibName53=C:/Program Files/KiCad/share/kicad/library/Diode_Laser
LibName54=C:/Program Files/KiCad/share/kicad/library/display
LibName55=C:/Program Files/KiCad/share/kicad/library/Display_Character
LibName56=C:/Program Files/KiCad/share/kicad/library/Display_Graphic
LibName57=C:/Program Files/KiCad/share/kicad/library/dk_Addressable-Specialty
LibName58=C:/Program Files/KiCad/share/kicad/library/dk_Alarms-Buzzers-and-Sirens
LibName59=C:/Program Files/KiCad/share/kicad/library/dk_Automotive-Relays
LibName60=C:/Program Files/KiCad/share/kicad/library/dk_Balun
LibName61=C:/Program Files/KiCad/share/kicad/library/dk_Barrel-Audio-Connectors
LibName62=C:/Program Files/KiCad/share/kicad/library/dk_Battery-Holders-Clips-Contacts
LibName63=C:/Program Files/KiCad/share/kicad/library/dk_Clock-Timing-Clock-Generators-PLLs-Frequency-Synthesizers
LibName64=C:/Program Files/KiCad/share/kicad/library/dk_Clock-Timing-Programmable-Timers-and-Oscillators
LibName65=C:/Program Files/KiCad/share/kicad/library/dk_Clock-Timing-Real-Time-Clocks
LibName66=C:/Program Files/KiCad/share/kicad/library/dk_Coaxial-Connectors-RF
LibName67=C:/Program Files/KiCad/share/kicad/library/dk_Current-Transducers
LibName68=C:/Program Files/KiCad/share/kicad/library/dk_Data-Acquisition-ADCs-DACs-Special-Purpose
LibName69=C:/Program Files/KiCad/share/kicad/library/dk_Data-Acquisition-Analog-to-Digital-Converters-ADC
LibName70=C:/Program Files/KiCad/share/kicad/library/dk_Data-Acquisition-Digital-Potentiometers
LibName71=C:/Program Files/KiCad/share/kicad/library/dk_Data-Acquisition-Digital-to-Analog-Converters-DAC
LibName72=C:/Program Files/KiCad/share/kicad/library/dk_Data-Acquisition-Touch-Screen-Controllers
LibName73=C:/Program Files/KiCad/share/kicad/library/dk_DC-DC-Converters
LibName74=C:/Program Files/KiCad/share/kicad/library/dk_Digital-Isolators
LibName75=C:/Program Files/KiCad/share/kicad/library/dk_Diodes-Bridge-Rectifiers
LibName76=C:/Program Files/KiCad/share/kicad/library/dk_Diodes-Rectifiers-Arrays
LibName77=C:/Program Files/KiCad/share/kicad/library/dk_Diodes-Rectifiers-Single
LibName78=C:/Program Files/KiCad/share/kicad/library/dk_Diodes-Zener-Single
LibName79=C:/Program Files/KiCad/share/kicad/library/dk_Display-Modules-LCD-OLED-Graphic
LibName80=C:/Program Files/KiCad/share/kicad/library/dk_Display-Modules-LED-Character-and-Numeric
LibName81=C:/Program Files/KiCad/share/kicad/library/dk_D-Sub-Connectors
LibName82=C:/Program Files/KiCad/share/kicad/library/dk_Embedded-Microcontrollers
LibName83=C:/Program Files/KiCad/share/kicad/library/dk_Encoders
LibName84=C:/Program Files/KiCad/share/kicad/library/dk_Evaluation-Boards-Sensors
LibName85=C:/Program Files/KiCad/share/kicad/library/dk_Ferrite-Beads-and-Chips
LibName86=C:/Program Files/KiCad/share/kicad/library/dk_Fixed-Inductors
LibName87=C:/Program Files/KiCad/share/kicad/library/dk_Fuses
LibName88=C:/Program Files/KiCad/share/kicad/library/dk_Gas-Sensors
LibName89=C:/Program Files/KiCad/share/kicad/library/dk_Humidity-Moisture-Sensors
LibName90=C:/Program Files/KiCad/share/kicad/library/dk_Image-Sensors-Camera
LibName91=C:/Program Files/KiCad/share/kicad/library/dk_Infrared-UV-Visible-Emitters
LibName92=C:/Program Files/KiCad/share/kicad/library/dk_Inrush-Current-Limiters-ICL
LibName93=C:/Program Files/KiCad/share/kicad/library/dk_Interface-Analog-Switches-Multiplexers-Demultiplexers
LibName94=C:/Program Files/KiCad/share/kicad/library/dk_Interface-Analog-Switches-Special-Purpose
LibName95=C:/Program Files/KiCad/share/kicad/library/dk_Interface-Controllers
LibName96=C:/Program Files/KiCad/share/kicad/library/dk_Interface-Drivers-Receivers-Transceivers
LibName97=C:/Program Files/KiCad/share/kicad/library/dk_Interface-I-O-Expanders
LibName98=C:/Program Files/KiCad/share/kicad/library/dk_Interface-Modules
LibName99=C:/Program Files/KiCad/share/kicad/library/dk_Interface-Sensor-and-Detector-Interfaces
LibName100=C:/Program Files/KiCad/share/kicad/library/dk_Interface-Sensor-Capacitive-Touch
LibName101=C:/Program Files/KiCad/share/kicad/library/dk_Interface-Specialized
LibName102=C:/Program Files/KiCad/share/kicad/library/dk_LED-Indication-Discrete
LibName103=C:/Program Files/KiCad/share/kicad/library/dk_LEDs-Circuit-Board-Indicators-Arrays-Light-Bars-Bar-Graphs
LibName104=C:/Program Files/KiCad/share/kicad/library/dk_Linear-Amplifiers-Audio
LibName105=C:/Program Files/KiCad/share/kicad/library/dk_Linear-Amplifiers-Instrumentation-OP-Amps-Buffer-Amps
LibName106=C:/Program Files/KiCad/share/kicad/library/dk_Linear-Comparators
LibName107=C:/Program Files/KiCad/share/kicad/library/dk_Logic-Buffers-Drivers-Receivers-Transceivers
LibName108=C:/Program Files/KiCad/share/kicad/library/dk_Logic-Flip-Flops
LibName109=C:/Program Files/KiCad/share/kicad/library/dk_Logic-Gates-and-Inverters
LibName110=C:/Program Files/KiCad/share/kicad/library/dk_Logic-Multivibrators
LibName111=C:/Program Files/KiCad/share/kicad/library/dk_Logic-Shift-Registers
LibName112=C:/Program Files/KiCad/share/kicad/library/dk_Logic-Signal-Switches-Multiplexers-Decoders
LibName113=C:/Program Files/KiCad/share/kicad/library/dk_Logic-Translators-Level-Shifters
LibName114=C:/Program Files/KiCad/share/kicad/library/dk_Magnetic-Sensors-Compass-Magnetic-Field-Modules
LibName115=C:/Program Files/KiCad/share/kicad/library/dk_Magnetic-Sensors-Linear-Compass-ICs
LibName116=C:/Program Files/KiCad/share/kicad/library/dk_Magnetic-Sensors-Switches-Solid-State
LibName117=C:/Program Files/KiCad/share/kicad/library/dk_Memory
LibName118=C:/Program Files/KiCad/share/kicad/library/dk_Memory-Connectors-PC-Card-Sockets
LibName119=C:/Program Files/KiCad/share/kicad/library/dk_Microphones
LibName120=C:/Program Files/KiCad/share/kicad/library/dk_Modular-Connectors-Jacks
LibName121=C:/Program Files/KiCad/share/kicad/library/dk_Modular-Connectors-Jacks-With-Magnetics
LibName122=C:/Program Files/KiCad/share/kicad/library/dk_Motion-Sensors-Accelerometers
LibName123=C:/Program Files/KiCad/share/kicad/library/dk_Motion-Sensors-IMUs-Inertial-Measurement-Units
LibName124=C:/Program Files/KiCad/share/kicad/library/dk_Motion-Sensors-Tilt-Switches
LibName125=C:/Program Files/KiCad/share/kicad/library/dk_Navigation-Switches-Joystick
LibName126=C:/Program Files/KiCad/share/kicad/library/dk_Optical-Sensors-Ambient-Light-IR-UV-Sensors
LibName127=C:/Program Files/KiCad/share/kicad/library/dk_Optical-Sensors-Photo-Detectors-Remote-Receiver
LibName128=C:/Program Files/KiCad/share/kicad/library/dk_Optical-Sensors-Photodiodes
LibName129=C:/Program Files/KiCad/share/kicad/library/dk_Optical-Sensors-Phototransistors
LibName130=C:/Program Files/KiCad/share/kicad/library/dk_Optical-Sensors-Reflective-Analog-Output
LibName131=C:/Program Files/KiCad/share/kicad/library/dk_Optoisolators-Logic-Output
LibName132=C:/Program Files/KiCad/share/kicad/library/dk_Optoisolators-Transistor-Photovoltaic-Output
LibName133=C:/Program Files/KiCad/share/kicad/library/dk_Optoisolators-Triac-SCR-Output
LibName134=C:/Program Files/KiCad/share/kicad/library/dk_Oscillators
LibName135=C:/Program Files/KiCad/share/kicad/library/dk_PMIC-AC-DC-Converters-Offline-Switchers
LibName136=C:/Program Files/KiCad/share/kicad/library/dk_PMIC-Battery-Chargers
LibName137=C:/Program Files/KiCad/share/kicad/library/dk_PMIC-Battery-Management
LibName138=C:/Program Files/KiCad/share/kicad/library/dk_PMIC-Current-Regulation-Management
LibName139=C:/Program Files/KiCad/share/kicad/library/dk_PMIC-Full-Half-Bridge-Drivers
LibName140=C:/Program Files/KiCad/share/kicad/library/dk_PMIC-Gate-Drivers
LibName141=C:/Program Files/KiCad/share/kicad/library/dk_PMIC-LED-Drivers
LibName142=C:/Program Files/KiCad/share/kicad/library/dk_PMIC-Motor-Drivers-Controllers
LibName143=C:/Program Files/KiCad/share/kicad/library/dk_PMIC-OR-Controllers-Ideal-Diodes
LibName144=C:/Program Files/KiCad/share/kicad/library/dk_PMIC-Power-Distribution-Switches-Load-Drivers
LibName145=C:/Program Files/KiCad/share/kicad/library/dk_PMIC-Power-Management-Specialized
LibName146=C:/Program Files/KiCad/share/kicad/library/dk_PMIC-RMS-to-DC-Converters
LibName147=C:/Program Files/KiCad/share/kicad/library/dk_PMIC-Supervisors
LibName148=C:/Program Files/KiCad/share/kicad/library/dk_PMIC-Thermal-Management
LibName149=C:/Program Files/KiCad/share/kicad/library/dk_PMIC-V-F-and-F-V-Converters
LibName150=C:/Program Files/KiCad/share/kicad/library/dk_PMIC-Voltage-Reference
LibName151=C:/Program Files/KiCad/share/kicad/library/dk_PMIC-Voltage-Regulators-DC-DC-Switching-Controllers
LibName152=C:/Program Files/KiCad/share/kicad/library/dk_PMIC-Voltage-Regulators-DC-DC-Switching-Regulators
LibName153=C:/Program Files/KiCad/share/kicad/library/dk_PMIC-Voltage-Regulators-Linear
LibName154=C:/Program Files/KiCad/share/kicad/library/dk_PMIC-Voltage-Regulators-Special-Purpose
LibName155=C:/Program Files/KiCad/share/kicad/library/dk_Power-Relays-Over-2-Amps
LibName156=C:/Program Files/KiCad/share/kicad/library/dk_Pressure-Sensors-Transducers
LibName157=C:/Program Files/KiCad/share/kicad/library/dk_Programmable-Oscillators
LibName158=C:/Program Files/KiCad/share/kicad/library/dk_Pushbutton-Switches
LibName159=C:/Program Files/KiCad/share/kicad/library/dk_Rectangular-Connectors-Headers-Male-Pins
LibName160=C:/Program Files/KiCad/share/kicad/library/dk_Reed-Relays
LibName161=C:/Program Files/KiCad/share/kicad/library/dk_Resistor-Networks-Arrays
LibName162=C:/Program Files/KiCad/share/kicad/library/dk_RF-Amplifiers
LibName163=C:/Program Files/KiCad/share/kicad/library/dk_RF-Antennas
LibName164=C:/Program Files/KiCad/share/kicad/library/dk_RF-Demodulators
LibName165=C:/Program Files/KiCad/share/kicad/library/dk_RF-Detectors
LibName166=C:/Program Files/KiCad/share/kicad/library/dk_RF-Evaluation-and-Development-Kits-Boards
LibName167=C:/Program Files/KiCad/share/kicad/library/dk_RFID-RF-Access-Monitoring-ICs
LibName168=C:/Program Files/KiCad/share/kicad/library/dk_RF-Receivers
LibName169=C:/Program Files/KiCad/share/kicad/library/dk_RF-Switches
LibName170=C:/Program Files/KiCad/share/kicad/library/dk_RF-Transceiver-ICs
LibName171=C:/Program Files/KiCad/share/kicad/library/dk_RF-Transceiver-Modules
LibName172=C:/Program Files/KiCad/share/kicad/library/dk_RF-Transmitters
LibName173=C:/Program Files/KiCad/share/kicad/library/dk_Rotary-Potentiometers-Rheostats
LibName174=C:/Program Files/KiCad/share/kicad/library/dk_Sensors-Transducers_Accessories
LibName175=C:/Program Files/KiCad/share/kicad/library/dk_Signal-Relays-Up-to-2-Amps
LibName176=C:/Program Files/KiCad/share/kicad/library/dk_Slide-Switches
LibName177=C:/Program Files/KiCad/share/kicad/library/dk_Solid-State-Relays
LibName178=C:/Program Files/KiCad/share/kicad/library/dk_Specialized-ICs
LibName179=C:/Program Files/KiCad/share/kicad/library/dk_Specialized-Sensors
LibName180=C:/Program Files/KiCad/share/kicad/library/dk_Surge-Suppression-ICs
LibName181=C:/Program Files/KiCad/share/kicad/library/dk_Tactile-Switches
LibName182=C:/Program Files/KiCad/share/kicad/library/dk_Temperature-Sensors-Analog-and-Digital-Output
LibName183=C:/Program Files/KiCad/share/kicad/library/dk_Thermal-Cutoffs-Thermal-Fuses
LibName184=C:/Program Files/KiCad/share/kicad/library/dk_Thyristors-DIACs-SIDACs
LibName185=C:/Program Files/KiCad/share/kicad/library/dk_Thyristors-SCRs
LibName186=C:/Program Files/KiCad/share/kicad/library/dk_Thyristors-TRIACs
LibName187=C:/Program Files/KiCad/share/kicad/library/dk_Toggle-Switches
LibName188=C:/Program Files/KiCad/share/kicad/library/dk_Transistors-Bipolar-BJT-Arrays
LibName189=C:/Program Files/KiCad/share/kicad/library/dk_Transistors-Bipolar-BJT-RF
LibName190=C:/Program Files/KiCad/share/kicad/library/dk_Transistors-Bipolar-BJT-Single
LibName191=C:/Program Files/KiCad/share/kicad/library/dk_Transistors-Bipolar-BJT-Single-Pre-Biased
LibName192=C:/Program Files/KiCad/share/kicad/library/dk_Transistors-FETs-MOSFETs-Arrays
LibName193=C:/Program Files/KiCad/share/kicad/library/dk_Transistors-FETs-MOSFETs-RF
LibName194=C:/Program Files/KiCad/share/kicad/library/dk_Transistors-FETs-MOSFETs-Single
LibName195=C:/Program Files/KiCad/share/kicad/library/dk_Transistors-JFETs
LibName196=C:/Program Files/KiCad/share/kicad/library/dk_Trimmer-Potentiometers
LibName197=C:/Program Files/KiCad/share/kicad/library/dk_TVS-Diodes
LibName198=C:/Program Files/KiCad/share/kicad/library/dk_TVS-Mixed-Technology
LibName199=C:/Program Files/KiCad/share/kicad/library/dk_USB-DVI-HDMI-Connectors
LibName200=C:/Program Files/KiCad/share/kicad/library/Driver_Display
LibName201=C:/Program Files/KiCad/share/kicad/library/Driver_FET
LibName202=C:/Program Files/KiCad/share/kicad/library/Driver_LED
LibName203=C:/Program Files/KiCad/share/kicad/library/Driver_Motor
LibName204=C:/Program Files/KiCad/share/kicad/library/Driver_Relay
LibName205=C:/Program Files/KiCad/share/kicad/library/dsp
LibName206=C:/Program Files/KiCad/share/kicad/library/DSP_Freescale
LibName207=C:/Program Files/KiCad/share/kicad/library/DSP_Microchip_DSPIC33
LibName208=C:/Program Files/KiCad/share/kicad/library/DSP_Motorola
LibName209=C:/Program Files/KiCad/share/kicad/library/DSP_Texas
LibName210=C:/Program Files/KiCad/share/kicad/library/elec-unifil
LibName211=C:/Program Files/KiCad/share/kicad/library/ESD_Protection
LibName212=C:/Program Files/KiCad/share/kicad/library/Filter
LibName213=C:/Program Files/KiCad/share/kicad/library/FPGA_Microsemi
LibName214=C:/Program Files/KiCad/share/kicad/library/FPGA_Xilinx
LibName215=C:/Program Files/KiCad/share/kicad/library/FPGA_Xilinx_Artix7
LibName216=C:/Program Files/KiCad/share/kicad/library/FPGA_Xilinx_Kintex7
LibName217=C:/Program Files/KiCad/share/kicad/library/FPGA_Xilinx_Spartan6
LibName218=C:/Program Files/KiCad/share/kicad/library/FPGA_Xilinx_Virtex5
LibName219=C:/Program Files/KiCad/share/kicad/library/FPGA_Xilinx_Virtex6
LibName220=C:/Program Files/KiCad/share/kicad/library/FPGA_Xilinx_Virtex7
LibName221=C:/Program Files/KiCad/share/kicad/library/ftdi
LibName222=C:/Program Files/KiCad/share/kicad/library/gennum
LibName223=C:/Program Files/KiCad/share/kicad/library/GPU
LibName224=C:/Program Files/KiCad/share/kicad/library/Graphic
LibName225=C:/Program Files/KiCad/share/kicad/library/graphic_symbols
LibName226=C:/Program Files/KiCad/share/kicad/library/hc11
LibName227=C:/Program Files/KiCad/share/kicad/library/infineon
LibName228=C:/Program Files/KiCad/share/kicad/library/intel
LibName229=C:/Program Files/KiCad/share/kicad/library/Interface
LibName230=C:/Program Files/KiCad/share/kicad/library/Interface_CAN_LIN
LibName231=C:/Program Files/KiCad/share/kicad/library/Interface_CurrentLoop
LibName232=C:/Program Files/KiCad/share/kicad/library/Interface_Ethernet
LibName233=C:/Program Files/KiCad/share/kicad/library/Interface_Expansion
LibName234=C:/Program Files/KiCad/share/kicad/library/Interface_HID
LibName235=C:/Program Files/KiCad/share/kicad/library/Interface_LineDriver
LibName236=C:/Program Files/KiCad/share/kicad/library/Interface_Optical
LibName237=C:/Program Files/KiCad/share/kicad/library/Interface_Telecom
LibName238=C:/Program Files/KiCad/share/kicad/library/Interface_UART
LibName239=C:/Program Files/KiCad/share/kicad/library/Interface_USB
LibName240=C:/Program Files/KiCad/share/kicad/library/intersil
LibName241=C:/Program Files/KiCad/share/kicad/library/ir
LibName242=C:/Program Files/KiCad/share/kicad/library/Isolator
LibName243=C:/Program Files/KiCad/share/kicad/library/Isolator_Analog
LibName244=C:/Program Files/KiCad/share/kicad/library/Jumper
LibName245=C:/Program Files/KiCad/share/kicad/library/Lattice
LibName246=C:/Program Files/KiCad/share/kicad/library/LED
LibName247=C:/Program Files/KiCad/share/kicad/library/leds
LibName248=C:/Program Files/KiCad/share/kicad/library/LEM
LibName249=C:/Program Files/KiCad/share/kicad/library/linear
LibName250=C:/Program Files/KiCad/share/kicad/library/Logic_LevelTranslator
LibName251=C:/Program Files/KiCad/share/kicad/library/Logic_Programmable
LibName252=C:/Program Files/KiCad/share/kicad/library/maxim
LibName253=C:/Program Files/KiCad/share/kicad/library/MCU_AnalogDevices
LibName254=C:/Program Files/KiCad/share/kicad/library/MCU_Cypress
LibName255=C:/Program Files/KiCad/share/kicad/library/MCU_Espressif
LibName256=C:/Program Files/KiCad/share/kicad/library/MCU_Intel
LibName257=C:/Program Files/KiCad/share/kicad/library/MCU_Microchip_8051
LibName258=C:/Program Files/KiCad/share/kicad/library/MCU_Microchip_ATmega
LibName259=C:/Program Files/KiCad/share/kicad/library/MCU_Microchip_ATtiny
LibName260=C:/Program Files/KiCad/share/kicad/library/MCU_Microchip_AVR
LibName261=C:/Program Files/KiCad/share/kicad/library/MCU_Microchip_PIC10
LibName262=C:/Program Files/KiCad/share/kicad/library/MCU_Microchip_PIC12
LibName263=C:/Program Files/KiCad/share/kicad/library/MCU_Microchip_PIC16
LibName264=C:/Program Files/KiCad/share/kicad/library/MCU_Microchip_PIC18
LibName265=C:/Program Files/KiCad/share/kicad/library/MCU_Microchip_PIC24
LibName266=C:/Program Files/KiCad/share/kicad/library/MCU_Microchip_PIC32
LibName267=C:/Program Files/KiCad/share/kicad/library/MCU_Microchip_SAME
LibName268=C:/Program Files/KiCad/share/kicad/library/MCU_Microchip_SAML
LibName269=C:/Program Files/KiCad/share/kicad/library/MCU_Module
LibName270=C:/Program Files/KiCad/share/kicad/library/MCU_Nordic
LibName271=C:/Program Files/KiCad/share/kicad/library/MCU_NXP_ColdFire
LibName272=C:/Program Files/KiCad/share/kicad/library/MCU_NXP_HC11
LibName273=C:/Program Files/KiCad/share/kicad/library/MCU_NXP_HC12
LibName274=C:/Program Files/KiCad/share/kicad/library/MCU_NXP_HCS12
LibName275=C:/Program Files/KiCad/share/kicad/library/MCU_NXP_Kinetis
LibName276=C:/Program Files/KiCad/share/kicad/library/MCU_NXP_LPC
LibName277=C:/Program Files/KiCad/share/kicad/library/MCU_NXP_MAC7100
LibName278=C:/Program Files/KiCad/share/kicad/library/MCU_NXP_MCore
LibName279=C:/Program Files/KiCad/share/kicad/library/MCU_NXP_S08
LibName280=C:/Program Files/KiCad/share/kicad/library/MCU_Parallax
LibName281=C:/Program Files/KiCad/share/kicad/library/MCU_SiFive
LibName282=C:/Program Files/KiCad/share/kicad/library/MCU_SiliconLabs
LibName283=C:/Program Files/KiCad/share/kicad/library/MCU_ST_STM8
LibName284=C:/Program Files/KiCad/share/kicad/library/MCU_ST_STM32F0
LibName285=C:/Program Files/KiCad/share/kicad/library/MCU_ST_STM32F1
LibName286=C:/Program Files/KiCad/share/kicad/library/MCU_ST_STM32F2
LibName287=C:/Program Files/KiCad/share/kicad/library/MCU_ST_STM32F3
LibName288=C:/Program Files/KiCad/share/kicad/library/MCU_ST_STM32F4
LibName289=C:/Program Files/KiCad/share/kicad/library/MCU_ST_STM32F7
LibName290=C:/Program Files/KiCad/share/kicad/library/MCU_ST_STM32H7
LibName291=C:/Program Files/KiCad/share/kicad/library/MCU_ST_STM32L0
LibName292=C:/Program Files/KiCad/share/kicad/library/MCU_ST_STM32L1
LibName293=C:/Program Files/KiCad/share/kicad/library/MCU_ST_STM32L4
LibName294=C:/Program Files/KiCad/share/kicad/library/MCU_ST_STM32L4+
LibName295=C:/Program Files/KiCad/share/kicad/library/MCU_Texas
LibName296=C:/Program Files/KiCad/share/kicad/library/MCU_Texas_MSP430
LibName297=C:/Program Files/KiCad/share/kicad/library/Mechanical
LibName298=C:/Program Files/KiCad/share/kicad/library/memory
LibName299=C:/Program Files/KiCad/share/kicad/library/Memory_Controller
LibName300=C:/Program Files/KiCad/share/kicad/library/Memory_EEPROM
LibName301=C:/Program Files/KiCad/share/kicad/library/Memory_EPROM
LibName302=C:/Program Files/KiCad/share/kicad/library/Memory_Flash
LibName303=C:/Program Files/KiCad/share/kicad/library/Memory_NVRAM
LibName304=C:/Program Files/KiCad/share/kicad/library/Memory_RAM
LibName305=C:/Program Files/KiCad/share/kicad/library/Memory_ROM
LibName306=C:/Program Files/KiCad/share/kicad/library/Memory_UniqueID
LibName307=C:/Program Files/KiCad/share/kicad/library/microchip
LibName308=C:/Program Files/KiCad/share/kicad/library/microchip_dspic33dsc
LibName309=C:/Program Files/KiCad/share/kicad/library/microchip_pic10mcu
LibName310=C:/Program Files/KiCad/share/kicad/library/microchip_pic12mcu
LibName311=C:/Program Files/KiCad/share/kicad/library/microchip_pic16mcu
LibName312=C:/Program Files/KiCad/share/kicad/library/microchip_pic18mcu
LibName313=C:/Program Files/KiCad/share/kicad/library/microchip_pic24mcu
LibName314=C:/Program Files/KiCad/share/kicad/library/microchip_pic32mcu
LibName315=C:/Program Files/KiCad/share/kicad/library/microcontrollers
LibName316=C:/Program Files/KiCad/share/kicad/library/modules
LibName317=C:/Program Files/KiCad/share/kicad/library/Motor
LibName318=C:/Program Files/KiCad/share/kicad/library/motor_drivers
LibName319=C:/Program Files/KiCad/share/kicad/library/motorola
LibName320=C:/Program Files/KiCad/share/kicad/library/motors
LibName321=C:/Program Files/KiCad/share/kicad/library/msp430
LibName322=C:/Program Files/KiCad/share/kicad/library/nordicsemi
LibName323=C:/Program Files/KiCad/share/kicad/library/nxp
LibName324=C:/Program Files/KiCad/share/kicad/library/nxp_armmcu
LibName325=C:/Program Files/KiCad/share/kicad/library/onsemi
LibName326=C:/Program Files/KiCad/share/kicad/library/opto
LibName327=C:/Program Files/KiCad/share/kicad/library/Oscillator
LibName328=C:/Program Files/KiCad/share/kicad/library/Oscillators
LibName329=C:/Program Files/KiCad/share/kicad/library/philips
LibName330=C:/Program Files/KiCad/share/kicad/library/Potentiometer_Digital
LibName331=C:/Program Files/KiCad/share/kicad/library/power
LibName332=C:/Program Files/KiCad/share/kicad/library/Power_Management
LibName333=C:/Program Files/KiCad/share/kicad/library/Power_Protection
LibName334=C:/Program Files/KiCad/share/kicad/library/Power_Supervisor
LibName335=C:/Program Files/KiCad/share/kicad/library/powerint
LibName336=C:/Program Files/KiCad/share/kicad/library/pspice
LibName337=C:/Program Files/KiCad/share/kicad/library/Reference_Current
LibName338=C:/Program Files/KiCad/share/kicad/library/Reference_Voltage
LibName339=C:/Program Files/KiCad/share/kicad/library/references
LibName340=C:/Program Files/KiCad/share/kicad/library/regul
LibName341=C:/Program Files/KiCad/share/kicad/library/Regulator_Controller
LibName342=C:/Program Files/KiCad/share/kicad/library/Regulator_Current
LibName343=C:/Program Files/KiCad/share/kicad/library/Regulator_Linear
LibName344=C:/Program Files/KiCad/share/kicad/library/Regulator_SwitchedCapacitor
LibName345=C:/Program Files/KiCad/share/kicad/library/Regulator_Switching
LibName346=C:/Program Files/KiCad/share/kicad/library/Relay
LibName347=C:/Program Files/KiCad/share/kicad/library/Relay_SolidState
LibName348=C:/Program Files/KiCad/share/kicad/library/relays
LibName349=C:/Program Files/KiCad/share/kicad/library/RF
LibName350=C:/Program Files/KiCad/share/kicad/library/RF_AM_FM
LibName351=C:/Program Files/KiCad/share/kicad/library/RF_Amplifier
LibName352=C:/Program Files/KiCad/share/kicad/library/RF_Bluetooth
LibName353=C:/Program Files/KiCad/share/kicad/library/RF_GPS
LibName354=C:/Program Files/KiCad/share/kicad/library/RF_Mixer
LibName355=C:/Program Files/KiCad/share/kicad/library/RF_Module
LibName356=C:/Program Files/KiCad/share/kicad/library/RF_RFID
LibName357=C:/Program Files/KiCad/share/kicad/library/RF_Switch
LibName358=C:/Program Files/KiCad/share/kicad/library/RF_WiFi
LibName359=C:/Program Files/KiCad/share/kicad/library/RF_ZigBee
LibName360=C:/Program Files/KiCad/share/kicad/library/rfcom
LibName361=C:/Program Files/KiCad/share/kicad/library/RFSolutions
LibName362=C:/Program Files/KiCad/share/kicad/library/Sensor
LibName363=C:/Program Files/KiCad/share/kicad/library/Sensor_Audio
LibName364=C:/Program Files/KiCad/share/kicad/library/Sensor_Current
LibName365=C:/Program Files/KiCad/share/kicad/library/Sensor_Gas
LibName366=C:/Program Files/KiCad/share/kicad/library/Sensor_Humidity
LibName367=C:/Program Files/KiCad/share/kicad/library/Sensor_Magnetic
LibName368=C:/Program Files/KiCad/share/kicad/library/Sensor_Motion
LibName369=C:/Program Files/KiCad/share/kicad/library/Sensor_Optical
LibName370=C:/Program Files/KiCad/share/kicad/library/Sensor_Pressure
LibName371=C:/Program Files/KiCad/share/kicad/library/Sensor_Proximity
LibName372=C:/Program Files/KiCad/share/kicad/library/Sensor_Temperature
LibName373=C:/Program Files/KiCad/share/kicad/library/Sensor_Touch
LibName374=C:/Program Files/KiCad/share/kicad/library/Sensor_Voltage
LibName375=C:/Program Files/KiCad/share/kicad/library/sensors
LibName376=C:/Program Files/KiCad/share/kicad/library/silabs
LibName377=C:/Program Files/KiCad/share/kicad/library/siliconi
LibName378=C:/Program Files/KiCad/share/kicad/library/stm8
LibName379=C:/Program Files/KiCad/share/kicad/library/stm32
LibName380=C:/Program Files/KiCad/share/kicad/library/supertex
LibName381=C:/Program Files/KiCad/share/kicad/library/Switch
LibName382=C:/Program Files/KiCad/share/kicad/library/switches
LibName383=C:/Program Files/KiCad/share/kicad/library/texas
LibName384=C:/Program Files/KiCad/share/kicad/library/Timer
LibName385=C:/Program Files/KiCad/share/kicad/library/Timer_PLL
LibName386=C:/Program Files/KiCad/share/kicad/library/Timer_RTC
LibName387=C:/Program Files/KiCad/share/kicad/library/transf
LibName388=C:/Program Files/KiCad/share/kicad/library/Transformer
LibName389=C:/Program Files/KiCad/share/kicad/library/Transistor_Array
LibName390=C:/Program Files/KiCad/share/kicad/library/Transistor_BJT
LibName391=C:/Program Files/KiCad/share/kicad/library/Transistor_FET
LibName392=C:/Program Files/KiCad/share/kicad/library/Transistor_IGBT
LibName393=C:/Program Files/KiCad/share/kicad/library/transistors
LibName394=C:/Program Files/KiCad/share/kicad/library/Triac_Thyristor
LibName395=C:/Program Files/KiCad/share/kicad/library/ttl_ieee
LibName396=C:/Program Files/KiCad/share/kicad/library/Valve
LibName397=C:/Program Files/KiCad/share/kicad/library/valves
LibName398=C:/Program Files/KiCad/share/kicad/library/Video
LibName399=C:/Program Files/KiCad/share/kicad/library/wiznet
LibName400=C:/Program Files/KiCad/share/kicad/library/Worldsemi
LibName401=C:/Program Files/KiCad/share/kicad/library/Xicor
LibName402=C:/Program Files/KiCad/share/kicad/library/xilinx
LibName403=C:/Program Files/KiCad/share/kicad/library/zetex
LibName404=C:/Program Files/KiCad/share/kicad/library/Zilog
LibName405=power
LibName406=device
LibName407=switches
LibName408=relays
LibName409=motors
LibName410=transistors
LibName411=conn
LibName412=linear
LibName413=regul
LibName414=74xx
LibName415=cmos4000
LibName416=adc-dac
LibName417=memory
LibName418=xilinx
LibName419=microcontrollers
LibName420=dsp
LibName421=microchip
LibName422=analog_switches
LibName423=motorola
LibName424=texas
LibName425=intel
LibName426=audio
LibName427=interface
LibName428=digital-audio
LibName429=philips
LibName430=display
LibName431=cypress
LibName432=siliconi
LibName433=opto
LibName434=atmel
LibName435=contrib
LibName436=valves
